name: docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install LaTeX
      run: sudo apt install -y texlive-latex-extra texlive-science latexmk curl

    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Give permission to execute
      run: chmod u+x *.sh

    - name: Make all documents
      run: make

    - name: Upload exam
      uses: actions/upload-artifact@v2
      with:
        name: COMP_resol_exam.pdf
        path: exam/COMP_resol_exam.pdf

    - name: Upload test1
      uses: actions/upload-artifact@v2
      with:
        name: COMP_resol_test1.pdf
        path: tests/1/COMP_resol_test1.pdf
